### ISSUE TITLE
Missing cities

### ISSUE THREAD

**Issue by brunolemos** [lutangar/cities.json#1]
Where did you get this data?
Unfortunately it's missing cities, like mine: Guaratinguetá (state: São Paulo, country: BR)

**Comment by lutangar** [comment]
As stated in the `README.md`:
> This cities comes from the public domain database compiled by The Americas Open Geocode (AOG): 
> http://www.opengeocode.org/download.php#cities

This repository only consists in the conversion script `convert.js` and the resulting `json` dataset ` cities.json`.

**Comment by brunolemos** [comment]
Yeah, this link doesn't work.

**Comment by lutangar** [comment]
Haha, alright nice catch. If you find a better source for cities let me know, I could update this.

**Comment by AlexandroPerez** [comment]
@lutangar Have you tried [geonames.org](http://www.geonames.org/)

**Comment by lutangar** [comment]
Thanks for the suggestion @AlexandroPerez, I switched for http://www.geonames.org/ and now @brunolemos Guaratinguetá is now presents in the set. The license has been changed accordingly to the source database licence.
