### ISSUE TITLE
Add state/region to differentiate cities with similar names

### ISSUE THREAD

**Issue by AlexandroPerez** [lutangar/cities.json#2]
Currently there is no way to differentiate cities with the same name if they belong to the same country besides the lat-lon. Perhaps, since this is in json format, add the state/region to cities with similar names? This way there is no need to add the state/region to all cities.

**Comment by seanahrens** [comment]
I second this. For use in the United States, not having State names makes this dataset not practical. States in the US are of similar size to many world countries, and often have the same names as cities in other states.

**Comment by Hebertico** [comment]
Same over here

**Comment by pyramation** [comment]
I just came here for this reason, so many duplicate city names across US.

**Comment by ChrisLahaye** [comment]
@lutangar are there any plans for this?

**Comment by joelacus** [comment]
I've forked this and created two new files, one with US state names, and the other with US state abbreviations.
I've submitted a pull request, but you can download the files now from [here](https://github.com/joelacus/cities.json).
