### ISSUE TITLE
Publish to npm? :)

### ISSUE THREAD

**Issue by jcguarinpenaranda** [lutangar/cities.json#3]
First of all I want to give you a BIG thank you for this amazing work.

I was wondering, though, If it would be possible to publish this package to npm? So we can use it on server-side applications. I don't know if that would be the best strategy but I these main strenghts:
* One could easily update one's service by upgrading the package version
* Server-side we would not have to contact any remote database thus reducing the latency issues

I think about the npm package `countries-list`, that is hosted in Github on https://github.com/annexare/Countries 

I don't know if there would be any performance issues given the size of the generated file, but I would like to open the discussion to know what you think about.

**Comment by lutangar** [comment]
Glad to know it's helpful! 

This package is *already* available on npm:
`npm install --save cities.json`

Of course, there would be a big memory footprint if you require/import this file as is, but this is doable tho. I wouldn't advise it but for a one-shot script.
Another strategy would consists in loading these data into a database first.
